id: PFFF88DAB
initial_creation_type: input
source_metadata:
  title: Katok Getse Gyurme Tenpa Gyaltsen
  language: en
  description: 'Texts by and about Katok Getse Gyurme Tenpa Gyaltsen (kaḥ thog dge
    rtse ''gyur med bstan pa rgyal mtshan, 1954–2018), who was the seventh head of
    the Nyingma tradition:'
  volume:
    5fc8c4ad91ef457a8e8410143b0c85d3:
      title: Prayer of Aspiration for the Buddhist Teachings to Flourish in Taiwan
      parent: Aspiration Prayers
created_at: '2022-03-01T00:14:01.758500'
last_modified_at: '2022-03-01T00:14:01.758505'
